---
_extends: .github

repository:
  name: qTox
  description: Powerful Tox chat client that follows the Tox design guidelines.
  homepage: https://qtox.github.io/
  topics: tox, chat
  has_issues: false
