---
language: cpp
os: linux
cache: ccache

addons:
  apt:
    sources:
      - sourceline: 'ppa:mc3man/xerus-media'
    packages:
      # qt
      - libqt5svg5-dev
      - libqt5opengl5-dev
      - qttools5-dev
      - qt5-default
      # others
      - ffmpeg
      - libasound-dev
      - libass-dev
      - libfdk-aac-dev
      - libgtk2.0-dev
      - libmp3lame-dev
      - libogg-dev
      - libopenal-dev
      - libopencore-amrnb-dev
      - libopencore-amrwb-dev
      - libopus-dev
      - libqrencode-dev
      - libsdl1.2-dev
      - libsdl2-dev
      - libsodium-dev
      - libsoxr-dev
      - libspeex-dev
      - libsqlcipher-dev
      - libswscale-dev
      - libtheora-dev
      - libva-dev
      - libvdpau-dev
      - libvidstab-dev
      - libvorbis-dev
      - libvpx-dev
      - libwavpack-dev
      - libx264-dev
      - libx265-dev
      - libxv-dev
      - libxvidcore-dev

install:
  - git clone --depth=1 https://github.com/TokTok/c-toxcore
  - (cd c-toxcore && cmake . && make -j$(nproc) && sudo make install)
  - git clone --depth=1 https://github.com/sekrit-twc/zimg
  - (cd zimg && autoreconf -fi && ./configure && make -j$(nproc) && sudo make install)

script:
  - cmake .
  - make -j$(nproc)
  - make test
  - sudo make install
