sudo: true
dist: trusty
language: cpp

addons:
  apt:
    sources:
      - mc3man/trusty-media
      - chris-lea/libsodium
    packages:
      - ffmpeg
      - libasound-dev
      - libass-dev
      - libfdk-aac-dev
      - libgtk2.0-dev
      - libmp3lame-dev
      - libogg-dev
      - libopenal-dev
      - libopencore-amrnb-dev
      - libopencore-amrwb-dev
      - libopus-dev
      - libqrencode-dev
      - libqt5svg5-dev
      - libsdl1.2-dev
      - libsdl2-dev
      - libsodium-dev
      - libsoxr-dev
      - libspeex-dev
      - libsqlcipher-dev
      - libswscale-dev
      - libva-dev
      - libvdpau-dev
      - libvidstab-dev
      - libvorbis-dev
      - libvpx-dev
      - libwavpack-dev
      - libx264-dev
      - libx265-dev
      - libxv-dev
      - libxvidcore-dev
      - qttools5-dev
      - qttools5-dev-tools

matrix:
  include:
    - os: linux
      env: JOB=test ENV=linux
    - os: linux
      env: JOB=deploy ENV=linux
    - os: linux
      env: JOB=deploy ENV=windows ARCH=i686 LIBTYPE=shared
      services:
        - docker
    - os: linux
      env: JOB=deploy ENV=windows ARCH=x86_64 LIBTYPE=shared
      services:
        - docker
    - os: osx
      env: JOB=deploy ENV=osx

install:      .travis/phase $JOB $ENV install
script:       .travis/phase $JOB $ENV script
after_script: .travis/phase $JOB $ENV after_script

branches:
  only:
    - master
