---
language: cpp
compiler: clang
dist: xenial
os: linux

addons:
  apt:
    packages:
      # qt
      - libqt5svg5-dev
      - libqt5opengl5-dev
      - qtmultimedia5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qt5-default
      # others
      - libasound-dev
      - libsqlcipher-dev

install:
  - cd ..
  - git clone --depth=1 https://github.com/TokTok/toktok-stack
  - rmdir toktok-stack/qtox
  - mv qTox toktok-stack/qtox
  - cd toktok-stack
  - git submodule update --init --depth=1 c-toxcore
  # Download bazel.
  - source tools/setup-bazel
  - tools/setup-ci

script:
  - bazel test //qtox/... -k

# Only build pull requests and releases, don't build master on pushes,
# except through api or cron.
if: type IN (pull_request, api, cron) OR tag IS present
