---
language: cpp
compiler: clang
dist: xenial
os: linux

addons:
  apt:
    packages:
      # qt
      - libqt5svg5-dev
      - libqt5opengl5-dev
      - qttools5-dev
      - qt5-default
      # others
      - libasound-dev
      - libopenal-dev

install:
  - cd ..
  - git clone --branch=update-repos --depth=1 https://github.com/iphydf/toktok-stack
  - rmdir toktok-stack/qtox
  - mv qTox toktok-stack/qtox
  - cd toktok-stack
  - git submodule update --init --depth=1 c-toxcore
  - ln -s /usr/lib/x86_64-linux-gnu/qt5/bin third_party/qt/bin
  - ln -s /usr/include/x86_64-linux-gnu/qt5 third_party/qt/include
  - ln -s /usr/lib/x86_64-linux-gnu third_party/qt/lib
  - tools/setup-ci
  # Download bazel.
  - wget https://github.com/bazelbuild/bazel/releases/download/2.2.0/bazel-2.2.0-installer-linux-x86_64.sh
  - sha256sum -c tools/bazel-2.2.0-installer-linux-x86_64.sh.sha256
  - chmod +x bazel-2.2.0-installer-linux-x86_64.sh
  - ./bazel-2.2.0-installer-linux-x86_64.sh --user
  - export PATH=$HOME/bin:$PATH

script:
  - bazel test //qtox/... -k
